### PR TITLE
Compatibility with Gradle 7

### PR DESCRIPTION
**Pull request by vvslepkan**
Source: https://github.com/software-mansion/react-native-reanimated/issues/3119

### CODE REVIEW

**Comment by hadfieldn** [comment]
Came here needing the same fix. Would love to get this merged in.

**Comment by iamolegga** [comment]
Thanks for the PR, I should check this before merging, will try to do this within one week, cause I'm a bit busy with my offline life at the moment

**Comment by expouic** [comment]
One more that needs this fix :)

**Comment by iamolegga** [comment]
Sorry, I couldn't find time for testing, let's merge it as is for now. Just one question, is this a breaking change or this will work for a previous version?

**Comment by diogotcorreia** [comment]
@iamolegga It will work with Gradle 6

**Comment by iamolegga** [comment]
just published in **3.1.0**

**Pull request merged**
